In [31]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_csv("by_claude.csv")

In [33]:
df = pd.read_csv("by_claude.csv", engine="python", on_bad_lines="skip")

In [35]:
df.head()

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7
0,NaN,NaN,NaN,"Report Generated On Wednesday, 22-April-2026",NaN,NaN,NaN
1,NaN,NaN,NaN,Movement Report,NaN,NaN,NaN
2,Report For:,01-March-2026 00:00:00 - 31-March-2026 23:59:59,NaN,NaN,NaN,NaN,NaN
3,Total Distance,NaN,Total Fuel Burned,NaN,NaN,NaN,NaN
4,3496.77 Km,NaN,437.1 ltrs,NaN,NaN,NaN,NaN

In [36]:
df.duplicated().sum()

np.int64(4189)

In [8]:
df[df.duplicated]

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7
8,3496.77 Km,NaN,437.1 ltrs,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,"Report Generated On Wednesday, 22-April-2026",NaN,NaN,NaN
23,NaN,NaN,NaN,Movement Report,NaN,NaN,NaN
24,Start Date,Ignition,Speed,Status Location,Latitude,Longitude,Distance
25,dd/mm/yy,NaN,Km/Hr,NaN,NaN,NaN,km
...,...,...,...,...,...,...,...
13745,NaN,NaN,NaN,Movement Report,NaN,NaN,NaN
13746,Start Date,Ignition,Speed,Status Location,Latitude,Longitude,Distance
13747,dd/mm/yy,NaN,Km/Hr,NaN,NaN,NaN,km
13749,NaN,NaN,NaN,"Sindh, 75010, Pakistan",NaN,NaN,NaN
13751,NaN,NaN,NaN,Pakistan,NaN,NaN,NaN

In [9]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [10]:
df = df.drop_duplicates()

In [37]:
df.head(10)

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7
0,NaN,NaN,NaN,"Report Generated On Wednesday, 22-April-2026",NaN,NaN,NaN
1,NaN,NaN,NaN,Movement Report,NaN,NaN,NaN
2,Report For:,01-March-2026 00:00:00 - 31-March-2026 23:59:59,NaN,NaN,NaN,NaN,NaN
3,Total Distance,NaN,Total Fuel Burned,NaN,NaN,NaN,NaN
4,3496.77 Km,NaN,437.1 ltrs,NaN,NaN,NaN,NaN
5,Vehicle # JF-7479,NaN,Make: TOYOTA,NaN,NaN,NaN,NaN
6,Engine # 1KD-2023876,NaN,Chassis # JF-7479,NaN,NaN,NaN,NaN
7,Distance,NaN,Fuel Burned,NaN,NaN,NaN,NaN
8,3496.77 Km,NaN,437.1 ltrs,NaN,NaN,NaN,NaN
9,Start Date,Ignition,Speed,Status Location,Latitude,Longitude,Distance

In [38]:
df = df.drop(df.index[7:])

In [24]:
df.columns = ["Ignition","Speed","Status","Location","Latitude","Longitude","Distance"]

In [39]:
df.head()

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7
7,Distance,NaN,Fuel Burned,NaN,NaN,NaN,NaN
8,3496.77 Km,NaN,437.1 ltrs,NaN,NaN,NaN,NaN
9,Start Date,Ignition,Speed,Status Location,Latitude,Longitude,Distance
10,dd/mm/yy,NaN,Km/Hr,NaN,NaN,NaN,km
11,01/03/2026 00:29 AM,OFF,0,"Stop 0Km from Pipro Goth, Shah Town, Bin Qasim...",24.8545916,67.3337116,0