# Pandas

pandas working on both types of data numerical and categorical

### pandas have two data types

### 1) pandas Series object (Series)

#### A Series is a one-dimensional array-like object containing a sequence of values

In [2]:
import pandas as pd

In [4]:
s1 = pd.Series([1,2,34,21,12131,33,12])
s1

0        1
1        2
2       34
3       21
4    12131
5       33
6       12
dtype: int64

Indexing in Series

In [6]:
s2 = pd.Series([1,2,34,21,12131,33,12], 
               index=["ali", "jahanzeb","imran", "Irfan", "kashif", "kamran", "saqib"]) 
s2

ali             1
jahanzeb        2
imran          34
Irfan          21
kashif      12131
kamran         33
saqib          12
dtype: int64

In [7]:
s2.values

array([    1,     2,    34,    21, 12131,    33,    12])

In [8]:
s2.index

Index(['ali', 'jahanzeb', 'imran', 'Irfan', 'kashif', 'kamran', 'saqib'], dtype='object')

In [11]:
s2["imran"]

np.int64(34)

In [12]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [14]:
obj_series = pd.Series(sdata)
obj_series

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

### 2) pandas Data Frame object (DataFrame)

In [15]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [16]:
data_frame = pd.DataFrame(data)

In [17]:
data_frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [18]:
df = pd.read_excel("employee_data.xlsx")

In [20]:
df.head()

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645

In [21]:
df.shape

(35, 9)

In [22]:
df.size

315

In [23]:
df.tail()

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631

In [25]:
df.sample(5)

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921

In [30]:
df["First Name"].notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
25    True
26    True
27    True
28    True
29    True
30    True
31    True
32    True
33    True
34    True
Name: First Name, dtype: bool

In [32]:
df[[ "Age","First Name","Salary"]]

    Age First Name  Salary
0    35     Aditi    80000
1    35       Sona   70000
2    36       Devi   65000
3    42     Anjali   62000
4    29      Sahil   62000
5    42     Adhira   62000
6    42      Divya   52500
7    52       Amar   52100
8    28       Jaya   52000
9    35      Candy   52000
10   35     Sudhir   52000
11   28     Raghav   51000
12   36    Amitabh   51000
13   45      Kanak   50500
14   40      Tulsi   45200
15   50    Jasleen   45000
16   44        Nil   42000
17   28      Anand   42000
18   29    Atharva   41000
19   26      Charu   40000
20   35       Ajay   36000
21   36        Jai   35500
22   35    Ishaan    35000
23   42     Dhruva   35000
24   31      Artha   35000
25   51     Shaila   35000
26   52      Inaya   30000
27   41      Darsh   30000
28   30      Mihir   30000
29   50    Agastya   25500
30   37      Shaan   25200
31   51      Navi    25000
32   36      Ambar   25000
33   28      Lata    25000
34   25      Anaya   24100

In [33]:
df.

0     80000
1     70000
2     65000
3     62000
4     62000
5     62000
6     52500
7     52100
8     52000
9     52000
10    52000
11    51000
12    51000
13    50500
14    45200
15    45000
16    42000
17    42000
18    41000
19    40000
20    36000
21    35500
22    35000
23    35000
24    35000
25    35000
26    30000
27    30000
28    30000
29    25500
30    25200
31    25000
32    25000
33    25000
34    24100
Name: Salary, dtype: int64

In [36]:
df.Salary.min()

24100

In [57]:
df["tax%"] = df.Salary.apply(lambda x: 20 if x>=50000 else 15 if x>=40000 else 10)

In [53]:
df

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%,tax
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,20,16000.0
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,20,14000.0
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,20,13000.0
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,20,12400.0
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,20,12400.0
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,20,12400.0
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,20,10500.0
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,20,10420.0
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,20,10400.0
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,20,10400.0
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,20,10400.0
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,20,10200.0
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,20,10200.0
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,20,10100.0
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,15,6780.0
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,15,6750.0
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,15,6300.0
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,15,6300.0
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,15,6150.0
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,15,6000.0
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,10,3600.0
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,10,3550.0
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,10,3500.0
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,10,3500.0
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,10,3500.0
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,10,3500.0
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,10,3000.0
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,10,3000.0
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,10,3000.0
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,10,2550.0
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,10,2520.0
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,10,2500.0
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,10,2500.0
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,10,2500.0
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,10,2410.0

In [54]:
df["tax_amount"] = df.Salary.apply(lambda x: x * 0.2 if x>=50000 else x*0.15 if x>=40000 else x*0.1)

In [55]:
df

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%,tax,tax_amount
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,20,16000.0,16000.0
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,20,14000.0,14000.0
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,20,13000.0,13000.0
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,20,12400.0,12400.0
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,20,12400.0,12400.0
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,20,12400.0,12400.0
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,20,10500.0,10500.0
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,20,10420.0,10420.0
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,20,10400.0,10400.0
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,20,10400.0,10400.0
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,20,10400.0,10400.0
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,20,10200.0,10200.0
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,20,10200.0,10200.0
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,20,10100.0,10100.0
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,15,6780.0,6780.0
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,15,6750.0,6750.0
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,15,6300.0,6300.0
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,15,6300.0,6300.0
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,15,6150.0,6150.0
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,15,6000.0,6000.0
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,10,3600.0,3600.0
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,10,3550.0,3550.0
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,10,3500.0,3500.0
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,10,3500.0,3500.0
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,10,3500.0,3500.0
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,10,3500.0,3500.0
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,10,3000.0,3000.0
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,10,3000.0,3000.0
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,10,3000.0,3000.0
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,10,2550.0,2550.0
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,10,2520.0,2520.0
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,10,2500.0,2500.0
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,10,2500.0,2500.0
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,10,2500.0,2500.0
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,10,2410.0,2410.0

In [58]:
df.drop(columns=["tax"])

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%,tax_amount
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,20,16000.0
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,20,14000.0
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,20,13000.0
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,20,12400.0
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,20,12400.0
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,20,12400.0
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,20,10500.0
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,20,10420.0
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,20,10400.0
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,20,10400.0
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,20,10400.0
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,20,10200.0
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,20,10200.0
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,20,10100.0
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,15,6780.0
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,15,6750.0
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,15,6300.0
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,15,6300.0
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,15,6150.0
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,15,6000.0
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,10,3600.0
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,10,3550.0
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,10,3500.0
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,10,3500.0
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,10,3500.0
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,10,3500.0
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,10,3000.0
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,10,3000.0
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,10,3000.0
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,10,2550.0
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,10,2520.0
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,10,2500.0
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,10,2500.0
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,10,2500.0
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,10,2410.0

In [62]:
# df["Net Salary "] = df.Salary.apply(lambda x: x - (x * 0.2) if x>=50000 else x - (x*0.15) if x>=40000 else x - (x*0.1))

df["Net Salary "] = df["Salary"] - df["tax_amount"]

In [63]:
df

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%,tax,tax_amount,Net Salary
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,20,16000.0,16000.0,64000.0
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,20,14000.0,14000.0,56000.0
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,20,13000.0,13000.0,52000.0
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,20,12400.0,12400.0,49600.0
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,20,12400.0,12400.0,49600.0
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,20,12400.0,12400.0,49600.0
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,20,10500.0,10500.0,42000.0
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,20,10420.0,10420.0,41680.0
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,20,10400.0,10400.0,41600.0
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,20,10400.0,10400.0,41600.0
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,20,10400.0,10400.0,41600.0
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,20,10200.0,10200.0,40800.0
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,20,10200.0,10200.0,40800.0
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,20,10100.0,10100.0,40400.0
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,15,6780.0,6780.0,38420.0
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,15,6750.0,6750.0,38250.0
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,15,6300.0,6300.0,35700.0
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,15,6300.0,6300.0,35700.0
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,15,6150.0,6150.0,34850.0
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,15,6000.0,6000.0,34000.0
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,10,3600.0,3600.0,32400.0
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,10,3550.0,3550.0,31950.0
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,10,3500.0,3500.0,31500.0
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,10,3500.0,3500.0,31500.0
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,10,3500.0,3500.0,31500.0
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,10,3500.0,3500.0,31500.0
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,10,3000.0,3000.0,27000.0
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,10,3000.0,3000.0,27000.0
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,10,3000.0,3000.0,27000.0
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,10,2550.0,2550.0,22950.0
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,10,2520.0,2520.0,22680.0
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,10,2500.0,2500.0,22500.0
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,10,2500.0,2500.0,22500.0
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,10,2500.0,2500.0,22500.0
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,10,2410.0,2410.0,21690.0