In [1]:
import pandas as pd

In [2]:
emp = pd.read_excel("employee_data.xlsx")

In [3]:
emp

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631

In [4]:
emp.iloc[:5,2:6]

   Gender  Age  Salary  Expenditure
0  Female   35   80000        65000
1  Female   35   70000        58000
2  Female   36   65000        60000
3  Female   42   62000        50000
4    Male   29   62000        57000

In [5]:
emp.loc[:5,"First Name" : "Savings"]

  First Name Last Name  Gender  Age  Salary  Expenditure  Savings
0     Aditi     Mishra  Female   35   80000        65000    15000
1       Sona     Singh  Female   35   70000        58000    12000
2       Devi    Thakur  Female   36   65000        60000     5000
3     Anjali      Kaur  Female   42   62000        50000    12000
4      Sahil  Deshmukh    Male   29   62000        57000     5000
5     Adhira       Das    Male   42   62000        59000     3000

In [6]:
emp.Gender == "Female"

0      True
1      True
2      True
3      True
4     False
5     False
6      True
7     False
8      True
9      True
10    False
11    False
12    False
13    False
14     True
15     True
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27    False
28    False
29    False
30    False
31     True
32    False
33     True
34     True
Name: Gender, dtype: bool

In [18]:
emp[(emp.Gender == "Female") & (emp.Age >= 30) & (emp.Salary <= 30000 )]
emp.head()

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645

In [20]:
emp[(emp["Savings"] + emp["Expenditure"]) >= 52000][["First Name","Last Name","Age","Salary"]]

   First Name Last Name  Age  Salary
0      Aditi     Mishra   35   80000
1        Sona     Singh   35   70000
2        Devi    Thakur   36   65000
3      Anjali      Kaur   42   62000
4       Sahil  Deshmukh   29   62000
5      Adhira       Das   42   62000
6       Divya     Bhatt   42   52500
7        Amar       Rao   52   52100
8        Jaya     Mehta   28   52000
9       Candy     Patel   35   52000
10     Sudhir    Mishra   35   52000