In [1]:
import pandas as pd

In [2]:
customers_df = pd.read_excel("practice_datasets/joins_practice_data.xlsx" , sheet_name=0)
countries_df = pd.read_excel("practice_datasets/joins_practice_data.xlsx" , sheet_name=1)
orders_df = pd.read_excel("practice_datasets/joins_practice_data.xlsx" , sheet_name=2)
products_df = pd.read_excel("practice_datasets/joins_practice_data.xlsx" , sheet_name=3)
categories_df = pd.read_excel("practice_datasets/joins_practice_data.xlsx" , sheet_name=4)

In [3]:
all_sheets = pd.read_excel('practice_datasets/joins_practice_data.xlsx', sheet_name=None)
for name, df in all_sheets.items():
    print(f"Sheet: {name}")

Sheet: customers
Sheet: countries
Sheet: orders
Sheet: products
Sheet: categories

# JOIN Practice Exercises

## 📊 Dataset Overview

| Table        | Rows | Key Column     | Joins To              |
|--------------|------|----------------|-----------------------|
| customers    | 10   | customer_id    | orders, countries     |
| countries    | 9    | country_id     | customers             |
| orders       | 13   | order_id       | customers, products   |
| products     | 10   | product_id     | orders, categories    |
| categories   | 6    | category_id    | products              |
| employees    | 10   | employee_id    | employees (self-join) |

In [30]:
customers_df.merge(orders_df)

,customer_id,customer_name,email,city,country_id,order_id,product_id,order_date,quantity,status
0,1,Ali Hassan,ali@example.com,Karachi,1,1001,P01,2024-01-10,2,Delivered
1,1,Ali Hassan,ali@example.com,Karachi,1,1004,P05,2024-02-10,1,Delivered
2,2,Sara Khan,sara@example.com,Lahore,1,1002,P03,2024-01-15,1,Delivered
3,2,Sara Khan,sara@example.com,Lahore,1,1008,P02,2024-03-10,2,Shipped
4,3,James Brown,james@example.com,New York,2,1003,P02,2024-02-01,3,Shipped
5,4,Maria Garcia,maria@example.com,Madrid,3,1011,P05,2024-04-01,2,Shipped
6,5,Chen Wei,chen@example.com,Beijing,4,1005,P04,2024-02-20,2,Processing
7,6,Aisha Malik,aisha@example.com,Islamabad,1,1006,P01,2024-03-01,4,Delivered
8,7,John Smith,john@example.com,London,5,1007,P06,2024-03-05,1,Cancelled
9,8,Fatima Noor,fatima@example.com,Dubai,6,1012,P08,2024-04-05,1,Delivered
10,9,Raj Patel,raj@example.com,Mumbai,7,1009,P03,2024-03-15,1,Processing
11,10,Sophie Dubois,sophie@example.com,Paris,8,1010,P07,2024-03-20,3,Delivered

In [31]:
countries_df

   country_id    country_name       region
0           1        Pakistan         Asia
1           2   United States     Americas
2           3           Spain       Europe
3           4           China         Asia
4           5  United Kingdom       Europe
5           6             UAE  Middle East
6           7           India         Asia
7           8          France       Europe
8           9          Brazil     Americas

In [32]:
orders_df

    order_id  customer_id product_id order_date  quantity      status
0       1001          1.0        P01 2024-01-10         2   Delivered
1       1002          2.0        P03 2024-01-15         1   Delivered
2       1003          3.0        P02 2024-02-01         3     Shipped
3       1004          1.0        P05 2024-02-10         1   Delivered
4       1005          5.0        P04 2024-02-20         2  Processing
5       1006          6.0        P01 2024-03-01         4   Delivered
6       1007          7.0        P06 2024-03-05         1   Cancelled
7       1008          2.0        P02 2024-03-10         2     Shipped
8       1009          9.0        P03 2024-03-15         1  Processing
9       1010         10.0        P07 2024-03-20         3   Delivered
10      1011          4.0        P05 2024-04-01         2     Shipped
11      1012          8.0        P08 2024-04-05         1   Delivered
12      1013          NaN        P02 2024-04-10         1     Pending

In [36]:
customers_df.merge(orders_df).merge(countries_df).drop("country_id" ,axis=1)

,customer_id,customer_name,email,city,order_id,product_id,order_date,quantity,status,country_name,region
0,1,Ali Hassan,ali@example.com,Karachi,1001,P01,2024-01-10,2,Delivered,Pakistan,Asia
1,1,Ali Hassan,ali@example.com,Karachi,1004,P05,2024-02-10,1,Delivered,Pakistan,Asia
2,2,Sara Khan,sara@example.com,Lahore,1002,P03,2024-01-15,1,Delivered,Pakistan,Asia
3,2,Sara Khan,sara@example.com,Lahore,1008,P02,2024-03-10,2,Shipped,Pakistan,Asia
4,3,James Brown,james@example.com,New York,1003,P02,2024-02-01,3,Shipped,United States,Americas
5,4,Maria Garcia,maria@example.com,Madrid,1011,P05,2024-04-01,2,Shipped,Spain,Europe
6,5,Chen Wei,chen@example.com,Beijing,1005,P04,2024-02-20,2,Processing,China,Asia
7,6,Aisha Malik,aisha@example.com,Islamabad,1006,P01,2024-03-01,4,Delivered,Pakistan,Asia
8,7,John Smith,john@example.com,London,1007,P06,2024-03-05,1,Cancelled,United Kingdom,Europe
9,8,Fatima Noor,fatima@example.com,Dubai,1012,P08,2024-04-05,1,Delivered,UAE,Middle East
10,9,Raj Patel,raj@example.com,Mumbai,1009,P03,2024-03-15,1,Processing,India,Asia
11,10,Sophie Dubois,sophie@example.com,Paris,1010,P07,2024-03-20,3,Delivered,France,Europe

In [10]:
# countries_df.merge(customers_df)
pd.merge(countries_df,customers_df,how="outer")

,country_id,country_name,region,customer_id,customer_name,email,city
0,1,Pakistan,Asia,1.0,Ali Hassan,ali@example.com,Karachi
1,1,Pakistan,Asia,2.0,Sara Khan,sara@example.com,Lahore
2,1,Pakistan,Asia,6.0,Aisha Malik,aisha@example.com,Islamabad
3,2,United States,Americas,3.0,James Brown,james@example.com,New York
4,3,Spain,Europe,4.0,Maria Garcia,maria@example.com,Madrid
5,4,China,Asia,5.0,Chen Wei,chen@example.com,Beijing
6,5,United Kingdom,Europe,7.0,John Smith,john@example.com,London
7,6,UAE,Middle East,8.0,Fatima Noor,fatima@example.com,Dubai
8,7,India,Asia,9.0,Raj Patel,raj@example.com,Mumbai
9,8,France,Europe,10.0,Sophie Dubois,sophie@example.com,Paris
10,9,Brazil,Americas,NaN,NaN,NaN,NaN

In [8]:
countries_df

   country_id    country_name       region
0           1        Pakistan         Asia
1           2   United States     Americas
2           3           Spain       Europe
3           4           China         Asia
4           5  United Kingdom       Europe
5           6             UAE  Middle East
6           7           India         Asia
7           8          France       Europe
8           9          Brazil     Americas

In [9]:
customers_df

   customer_id  customer_name               email       city  country_id
0            1     Ali Hassan     ali@example.com    Karachi           1
1            2      Sara Khan    sara@example.com     Lahore           1
2            3    James Brown   james@example.com   New York           2
3            4   Maria Garcia   maria@example.com     Madrid           3
4            5       Chen Wei    chen@example.com    Beijing           4
5            6    Aisha Malik   aisha@example.com  Islamabad           1
6            7     John Smith    john@example.com     London           5
7            8    Fatima Noor  fatima@example.com      Dubai           6
8            9      Raj Patel     raj@example.com     Mumbai           7
9           10  Sophie Dubois  sophie@example.com      Paris           8

In [13]:
pd.merge(countries_df,customers_df,how="left") # it will use left dataframe

,country_id,country_name,region,customer_id,customer_name,email,city
0,1,Pakistan,Asia,1.0,Ali Hassan,ali@example.com,Karachi
1,1,Pakistan,Asia,2.0,Sara Khan,sara@example.com,Lahore
2,1,Pakistan,Asia,6.0,Aisha Malik,aisha@example.com,Islamabad
3,2,United States,Americas,3.0,James Brown,james@example.com,New York
4,3,Spain,Europe,4.0,Maria Garcia,maria@example.com,Madrid
5,4,China,Asia,5.0,Chen Wei,chen@example.com,Beijing
6,5,United Kingdom,Europe,7.0,John Smith,john@example.com,London
7,6,UAE,Middle East,8.0,Fatima Noor,fatima@example.com,Dubai
8,7,India,Asia,9.0,Raj Patel,raj@example.com,Mumbai
9,8,France,Europe,10.0,Sophie Dubois,sophie@example.com,Paris
10,9,Brazil,Americas,NaN,NaN,NaN,NaN